spring.application.name=policy-auditor-backend
spring.datasource.url=jdbc:mysql://localhost:3306/policy_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.show-sql=true